"""
User details stored locally in this python file.
The code used for generating this data is mentioned in comment below the users list.
"""

users = {'Eliseo@gardner.biz': 1, 'Jayne_Kuhic@sydney.com': 2, 'Nikita@garfield.biz': 3, 'Lew@alysha.tv': 4,
         'Hayden@althea.biz': 5, 'Presley.Mueller@myrl.com': 6, 'Dallas@ole.me': 7, 'Mallory_Kunze@marie.org': 8,
         'Meghan_Littel@rene.us': 9, 'Carmen_Keeling@caroline.name': 10, 'Veronica_Goodwin@timmothy.net': 11,
         'Oswald.Vandervort@leanne.org': 12, 'Kariane@jadyn.tv': 13, 'Nathan@solon.io': 14,
         'Maynard.Hodkiewicz@roberta.com': 15, 'Christine@ayana.info': 16, 'Preston_Hudson@blaise.tv': 17,
         'Vincenza_Klocko@albertha.name': 18, 'Madelynn.Gorczany@darion.biz': 19, 'Mariana_Orn@preston.org': 20,
         'Noemie@marques.me': 21, 'Khalil@emile.co.uk': 22, 'Sophia@arianna.co.uk': 23, 'Jeffery@juwan.us': 24,
         'Isaias_Kuhic@jarrett.net': 25, 'Russel.Parker@kameron.io': 26, 'Francesco.Gleason@nella.us': 27,
         'Ronny@rosina.org': 28, 'Jennings_Pouros@erica.biz': 29, 'Lurline@marvin.biz': 30, 'Buford@shaylee.biz': 31,
         'Maria@laurel.name': 32, 'Jaeden.Towne@arlene.tv': 33, 'Ethelyn.Schneider@emelia.co.uk': 34,
         'Georgianna@florence.io': 35, 'Raheem_Heaney@gretchen.biz': 36, 'Jacky@victoria.net': 37,
         'Piper@linwood.us': 38, 'Gaylord@russell.net': 39, 'Clare.Aufderhar@nicole.ca': 40,
         'Lucio@gladys.tv': 41, 'Shemar@ewell.name': 42, 'Jackeline@eva.tv': 43, 'Marianna_Wilkinson@rupert.io': 44,
         'Marcia@name.biz': 45, 'Jeremy.Harann@waino.me': 46, 'Pearlie.Kling@sandy.com': 47,
         'Manuela_Stehr@chelsie.tv': 48, 'Camryn.Weimann@doris.io': 49, 'Kiana_Predovic@yasmin.io': 50,
         'Laurie@lincoln.us': 51, 'Abigail.OConnell@june.org': 52, 'Laverne_Price@scotty.info': 53,
         'Kenton_Vandervort@friedrich.com': 54, 'Hayden_Olson@marianna.me': 55, 'Vince_Crist@heidi.biz': 56,
         'Darron.Nikolaus@eulah.me': 57, 'Ezra_Abshire@lyda.us': 58, 'Jameson@tony.info': 59,
         'Americo@estrella.net': 60, 'Aurelio.Pfeffer@griffin.ca': 61, 'Vesta_Crooks@dora.us': 62,
         'Margarett_Klein@mike.biz': 63, 'Freida@brandt.tv': 64, 'Mollie@agustina.name': 65, 'Janice@alda.io': 66,
         'Dashawn@garry.com': 67, 'Devan.Nader@ettie.me': 68, 'Joana.Schoen@leora.co.uk': 69,
         'Minerva.Anderson@devonte.ca': 70, 'Lavinia@lafayette.me': 71, 'Sabrina.Marks@savanah.name': 72,
         'Desmond_Graham@kailee.biz': 73, 'Gussie_Kunde@sharon.biz': 74, 'Richard@chelsie.co.uk': 75,
         'Gage_Turner@halle.name': 76, 'Alfred@sadye.biz': 77, 'Catharine@jordyn.com': 78,
         'Esther_Ratke@shayna.biz': 79, 'Evangeline@chad.net': 80, 'Newton.Kertzmann@anjali.io': 81,
         'Caleb_Herzog@rosamond.net': 82, 'Sage_Mueller@candace.net': 83, 'Bernie.Bergnaum@lue.com': 84,
         'Alexzander_Davis@eduardo.name': 85, 'Jacquelyn@krista.info': 86, 'Grover_Volkman@coty.tv': 87,
         'Jovanny@abigale.ca': 88, 'Isac_Schmeler@barton.com': 89, 'Sandy.Erdman@sabina.info': 90,
         'Alexandro@garry.io': 91, 'Vickie_Schuster@harley.net': 92, 'Roma_Doyle@alia.com': 93,
         'Tatum_Marks@jaylon.name': 94, 'Juston.Ruecker@scot.tv': 95, 'River.Grady@lavada.biz': 96,
         'Claudia@emilia.ca': 97, 'Torrey@june.tv': 98, 'Hildegard.Aufderhar@howard.com': 99,
         'Leone_Fay@orrin.com': 100, 'Lura@rod.tv': 101, 'Lottie.Zieme@ruben.us': 102, 'Winona_Price@jevon.me': 103,
         'Gabriel@oceane.biz': 104, 'Adolph.Ondricka@mozell.co.uk': 105, 'Allen@richard.biz': 106,
         'Nicholaus@mikayla.ca': 107, 'Kayla@susanna.org': 108, 'Gideon@amina.name': 109, 'Cassidy@maribel.io': 110,
         'Stefan.Crist@duane.ca': 111, 'Aniyah.Ortiz@monte.me': 112, 'Laverna@rico.biz': 113,
         'Derek@hildegard.net': 114, 'Tyrell@abdullah.ca': 115, 'Reyes@hailey.name': 116,
         'Danika.Dicki@mekhi.biz': 117, 'Alessandra.Nitzsche@stephania.us': 118, 'Matteo@marquis.net': 119,
         'Joshua.Spinka@toby.io': 120, 'Annabelle@cole.com': 121, 'Kacey@jamal.info': 122, 'Mina@mallie.name': 123,
         'Hudson.Blick@ruben.biz': 124, 'Domenic.Durgan@joaquin.name': 125, 'Alexie@alayna.org': 126,
         'Haven_Barrows@brant.org': 127, 'Marianne@maximo.us': 128, 'Fanny@danial.com': 129,
         'Trevion_Kuphal@bernice.name': 130, 'Emmet@guy.biz': 131, 'Megane.Fritsch@claude.name': 132,
         'Amya@durward.ca': 133, 'Jasen_Rempel@willis.org': 134, 'Harmony@reggie.com': 135,
         'Rosanna_Kunze@guy.net': 136, 'Ressie.Boehm@flossie.com': 137, 'Domenic.Wuckert@jazmyne.us': 138,
         'Rhett.OKon@brian.info': 139, 'Mathias@richmond.info': 140, 'Ottis@lourdes.org': 141, 'Estel@newton.ca': 142,
         'Bertha@erik.co.uk': 143, 'Joesph@matteo.info': 144, 'Alva@cassandre.net': 145, 'Vivienne@willis.org': 146,
         'Angelita@aliza.me': 147, 'Timmothy_Okuneva@alyce.tv': 148, 'Moriah_Welch@richmond.org': 149,
         'Ramiro_Kuhn@harmon.biz': 150, 'Cary@taurean.biz': 151, 'Tillman_Koelpin@luisa.com': 152,
         'Aleen@tania.biz': 153, 'Durward@cindy.com': 154, 'Lester@chauncey.ca': 155, 'Telly_Lynch@karl.co.uk': 156,
         'Makenzie@libbie.io': 157, 'Amiya@perry.us': 158, 'Meghan@akeem.tv': 159,
         'Mitchel.Williamson@fletcher.io': 160, 'Ashlee_Jast@emie.biz': 161, 'Antwan@lori.ca': 162,
         'Estelle@valentina.info': 163, 'Haylie@gino.name': 164, 'Blake_Spinka@robyn.info': 165,
         'Aimee.Bins@braeden.ca': 166, 'Eloy@vladimir.com': 167, 'Gabrielle@jada.co.uk': 168, 'Lee@dawn.net': 169,
         'Gideon.Hyatt@jalen.tv': 170, 'Gerda.Reynolds@ceasar.co.uk': 171, 'Ivah@brianne.net': 172,
         'Ethyl_Bogan@candace.co.uk': 173, 'Janelle_Guann@americo.info': 174, 'Alfonzo.Barton@kelley.co.uk': 175,
         'Esther@ford.me': 176, 'Naomie_Cronin@rick.co.uk': 177, 'Darryl@reginald.us': 178, 'Thea@aurelio.org': 179,
         'Carolyn@eloisa.biz': 180, 'Milan.Schoen@cortney.io': 181, 'Sabrina@raymond.biz': 182,
         'Hildegard@alford.ca': 183, 'Lowell.Pagac@omari.biz': 184, 'Vivianne@ima.us': 185,
         'Yasmin.Prohaska@hanna.co.uk': 186, 'Ursula.Kirlin@eino.org': 187, 'Nichole_Bartoletti@mozell.me': 188,
         'Lottie_Wyman@jasen.biz': 189, 'Dominique_Hermann@paige.ca': 190, 'Eugene@mohammed.net': 191,
         'Janick@marty.me': 192, 'Alena@deron.name': 193, 'Alphonso_Rosenbaum@valentin.co.uk': 194,
         'Frank@rosalind.name': 195, 'Jenifer_Lowe@reuben.ca': 196, 'Cecelia_Nitzsche@marty.com': 197,
         'Christop_Friesen@jordan.me': 198, 'Cooper_Boehm@damian.biz': 199, 'Amir@kaitlyn.org': 200,
         'Cleve@royal.us': 201, 'Donnell@polly.net': 202, 'Bonita@karl.biz': 203, 'Shea@angelina.biz': 204,
         'Omari@veronica.us': 205, 'Sophie@antoinette.ca': 206, 'Jessika@crystel.ca': 207,
         'Cesar_Volkman@letitia.biz': 208, 'Maureen_Mueller@lance.us': 209, 'Eriberto@geovany.ca': 210,
         'Faustino.Keeling@morris.co.uk': 211, 'Viola@aric.co.uk': 212, 'Felton_Huel@terrell.biz': 213,
         'Ferne_Bogan@angus.info': 214, 'Amy@reymundo.org': 215, 'Jaylan.Mayert@norbert.biz': 216,
         'Cristina.DAmore@destini.biz': 217, 'Ettie_Bashirian@lambert.biz': 218, 'Lizeth@kellen.org': 219,
         'Vladimir_Schumm@sharon.tv': 220, 'Madonna@will.com': 221, 'Cicero_Goldner@elenor.tv': 222,
         'Zella@jan.net': 223, 'Robin_Jacobi@verdie.net': 224, 'Lawson@demarco.co.uk': 225, 'Benton@jayde.tv': 226,
         'Melody@london.name': 227, 'Wyman.Swaniawski@marjorie.name': 228, 'Deborah@fletcher.co.uk': 229,
         'Dario@barton.info': 230, 'Kelton_McKenzie@danial.us': 231, 'Itzel@fritz.io': 232,
         'Jacquelyn_Kutch@kaya.co.uk': 233, 'Cheyanne.Schowalter@alycia.biz': 234, 'Macey@abbie.org': 235,
         'Freeda.Kirlin@eddie.ca': 236, 'Jennifer.Rowe@zoe.org': 237, 'Providenci.Heller@lenna.info': 238,
         'Emerald_Murazik@darrell.biz': 239, 'Joseph@corrine.com': 240, 'Lemuel@willow.name': 241,
         'Sven@gudrun.info': 242, 'Jennifer@shania.ca': 243, 'Eldora@madge.com': 244, 'Litzy@kaylie.io': 245,
         'Jaycee.Turner@euna.name': 246, 'Wilbert@cheyenne.ca': 247, 'Rebecca_Hessel@edna.net': 248,
         'Christiana@lawrence.info': 249, 'Samara@shaun.org': 250, 'Ayden_Hickle@stephany.tv': 251,
         'Carissa.Krajcik@jean.name': 252, 'Jayde@geovanny.io': 253, 'Ardella@khalid.biz': 254,
         'Delta_Welch@carleton.tv': 255, 'Carlee_Heathcote@harley.tv': 256, 'Delpha_Cormier@raymond.org': 257,
         'Glenna@caesar.org': 258, 'Hoyt_Dickens@napoleon.ca': 259, 'Wendell.Marvin@maegan.net': 260,
         'Virgie@layne.org': 261, 'Tia@kirsten.info': 262, 'Marco@jennyfer.biz': 263, 'Taya@milan.biz': 264,
         'Lenora@derrick.biz': 265, 'Carolina.Auer@polly.co.uk': 266, 'Jaylan.Braun@lane.us': 267,
         'Javier.Dicki@damien.org': 268, 'Khalil_Sawayn@tanya.net': 269, 'Tom.Russel@pattie.org': 270,
         'Ethelyn.Moore@gabe.info': 271, 'Evangeline_Kuvalis@santina.ca': 272, 'Orland@larry.name': 273,
         'Micaela.Powlowski@saul.me': 274, 'Imelda_Klein@melany.biz': 275, 'Matt.Moen@gilda.org': 276,
         'Rocky_Ullrich@rowena.name': 277, 'Natalia@caitlyn.ca': 278, 'Edythe@general.org': 279,
         'Aglae@gerardo.name': 280, 'Bridie@pearl.ca': 281, 'Aglae_Goldner@madisyn.co.uk': 282,
         'Owen_Moore@jeremy.org': 283, 'Jarred@dangelo.name': 284, 'Remington_Mohr@vincenza.me': 285,
         'Marco.Langworth@zoie.org': 286, 'Sedrick@mertie.tv': 287, 'Caleigh@eleanore.org': 288,
         'Paolo@cristopher.com': 289, 'Juana_Stamm@helmer.com': 290, 'Pascale@fleta.ca': 291,
         'Molly_Kertzmann@tristin.me': 292, 'Kailee.Larkin@amina.org': 293, 'Earnest.Sanford@lane.us': 294,
         'Abigail@trudie.com': 295, 'Name.Walter@zoie.me': 296, 'Norma@abraham.co.uk': 297,
         'Norberto_Weimann@ford.tv': 298, 'Nelson@charlene.biz': 299, 'Letha@liliane.ca': 300, 'Tiana@jeramie.tv': 301,
         'Lindsey@caitlyn.net': 302, 'Gregory.Kutch@shawn.info': 303, 'Murphy.Kris@casimer.me': 304,
         'Isidro_Kiehn@cristina.org': 305, 'Kenton_Carter@yolanda.co.uk': 306, 'Amos_Rohan@mozelle.tv': 307,
         'Timothy_Heathcote@jose.name': 308, 'Otilia.Daniel@elvie.io': 309, 'Toni@joesph.biz': 310,
         'Brisa@carrie.us': 311, 'Jasen.Kihn@devon.biz': 312, 'Efren.Konopelski@madisyn.us': 313,
         'Demetris.Bergnaum@fae.io': 314, 'Luella.Pollich@gloria.org': 315, 'Sister.Morissette@adelia.io': 316,
         'Shyanne@rick.info': 317, 'Freeman.Dare@ada.name': 318, 'Donnell@orland.org': 319, 'Robin@gaylord.biz': 320,
         'Danyka_Stark@jedidiah.name': 321, 'Margarita@casper.io': 322, 'Carlo@cortney.net': 323, 'Mina@nikita.tv': 324,
         'Violette@naomi.tv': 325, 'Lauren.Hodkiewicz@jarret.info': 326, 'Ernestina@piper.biz': 327,
         'Hettie_Morar@wiley.info': 328, 'Corbin.Hilll@modesto.biz': 329, 'Kenyatta@renee.io': 330,
         'Don@cameron.co.uk': 331, 'Jovan@aaliyah.tv': 332, 'Jeanie.McGlynn@enoch.ca': 333,
         'Garett_Gusikowski@abigale.me': 334, 'Doug@alana.co.uk': 335, 'Yoshiko@viviane.name': 336,
         'Micaela_Bins@mertie.us': 337, 'Loy@gillian.me': 338, 'Tyrel@hunter.net': 339,
         'Otilia.Schuppe@randal.com': 340, 'April@larissa.co.uk': 341, 'Glenna_Waters@retha.me': 342,
         'Cordelia.Oberbrunner@peyton.com': 343, 'Zander@santino.net': 344, 'Camila_Runolfsdottir@tressa.tv': 345,
         'Kirstin@tina.info': 346, 'Anthony.Koepp@savannah.tv': 347, 'Bradley.Lang@marilyne.tv': 348,
         'Loren@aric.biz': 349, 'Arjun@natalie.ca': 350, 'Solon.Goldner@judah.org': 351, 'Nina@osbaldo.name': 352,
         'Madaline@marlin.org': 353, 'Mike.Kozey@gladyce.us': 354, 'Orval.Treutel@arnold.me': 355,
         'Trent@samir.net': 356, 'Ashleigh@annette.ca': 357, 'Douglas@anabel.org': 358, 'Lowell@mossie.com': 359,
         'Jacquelyn@kristian.net': 360, 'Antwon@domenico.me': 361, 'Kenyon@retha.me': 362, 'Ben@elouise.net': 363,
         'Madisen.Hauck@barney.co.uk': 364, 'Dock.Parker@roy.biz': 365, 'Pablo.Ritchie@tyrique.co.uk': 366,
         'Sebastian_Gaylord@freda.org': 367, 'Lazaro@nadia.ca': 368, 'Jessy.Boyle@vernice.biz': 369,
         'Mitchel@hal.co.uk': 370, 'Lindsay@kiley.name': 371, 'Erika.Murazik@jorge.me': 372, 'Olin@edmund.ca': 373,
         'Lacey@novella.biz': 374, 'Sister@miller.net': 375, 'Raphaelle@miller.com': 376,
         'Jaren.Schiller@augusta.org': 377, 'Nikko_Reynolds@harry.me': 378, 'Afton.Medhurst@mina.info': 379,
         'Wilson.Nikolaus@fredrick.org': 380, 'Tomasa@lee.us': 381, 'Ally_Kassulke@rashad.ca': 382,
         'Reagan_Ziemann@ross.io': 383, 'Angelita@sally.org': 384, 'Lonzo@lorena.org': 385,
         'Alexandre@derrick.co.uk': 386, 'Judd@lucinda.ca': 387, 'Eleanora@karson.net': 388,
         'Enrico_Feil@liana.biz': 389, 'Beverly@perry.org': 390, 'Corene_Mante@rory.com': 391,
         'Emily_Flatley@ephraim.name': 392, 'Donna@frederik.com': 393, 'Kyleigh@ruben.org': 394,
         'Noemy.Hammes@lisette.net': 395, 'Margarett_Jenkins@harley.us': 396, 'Dexter.Pacocha@lauren.biz': 397,
         'Gennaro@jaunita.co.uk': 398, 'Jaycee@aimee.us': 399, 'Brennon@carmela.tv': 400, 'Vella.Mayer@colten.net': 401,
         'Caleb_Dach@kathleen.us': 402, 'Patience_Bahringer@dameon.biz': 403, 'Destinee.Simonis@jose.tv': 404,
         'Keshaun@brown.biz': 405, 'Merle.Schultz@marcel.org': 406, 'Malvina_Fay@louie.name': 407,
         'Domenick_Douglas@gabe.us': 408, 'Isaac@allene.net': 409, 'Marianna.Pacocha@george.net': 410,
         'Sister_Barton@lela.com': 411, 'Autumn.Lebsack@kasandra.ca': 412, 'Irma.OKon@arden.me': 413,
         'Alaina_Hammes@carter.info': 414, 'Alia@addison.org': 415, 'Aurelie_McKenzie@providenci.biz': 416,
         'May_Steuber@virgil.net': 417, 'Tessie@emilie.co.uk': 418, 'Priscilla@colten.org': 419,
         'Aylin@abigale.me': 420, 'Holden@kenny.io': 421, 'Guillermo_Dare@dorothea.tv': 422, 'Oscar@pearline.com': 423,
         'Jonathon_Feest@maxime.io': 424, 'Micah_Wolf@lennie.co.uk': 425, 'Shany@daisha.biz': 426,
         'Drew_Lemke@alexis.net': 427, 'Karina.Donnelly@liam.com': 428, 'Ahmed_Runolfsson@claire.name': 429,
         'Marilou_Halvorson@kane.io': 430, 'Bernie.Schoen@seamus.co.uk': 431, 'Joesph@darryl.net': 432,
         'Timmothy.Corwin@augustus.co.uk': 433, 'Julien_OHara@vance.io': 434, 'Susan.Bartell@euna.org': 435,
         'Selena.Quigley@johan.co.uk': 436, 'Clifton_Boehm@jacynthe.io': 437, 'Lizzie_Bartell@diamond.net': 438,
         'Yasmeen@golda.ca': 439, 'Adolf.Russel@clark.ca': 440, 'Elian@matilda.me': 441, 'Salma@francis.net': 442,
         'Orlando_Dickinson@vern.org': 443, 'Elda@orval.name': 444, 'Dennis@karley.net': 445, 'Jedediah@mason.io': 446,
         'Maryam@jack.name': 447, 'Rick@carlos.tv': 448, 'Vallie@jerrod.net': 449, 'Adolph.Hayes@isobel.biz': 450,
         'Duane_Dach@demario.us': 451, 'General@schuyler.org': 452, 'Stephania_Stanton@demond.biz': 453,
         'Reinhold.Schiller@kelly.info': 454, 'Royce@jaiden.co.uk': 455, 'Cassie@diana.org': 456,
         'Jena.OKeefe@adonis.net': 457, 'Magdalen@holly.io': 458, 'Nyah@otho.com': 459, 'Kara_Stokes@connie.co.uk': 460,
         'Conner@daron.info': 461, 'Nathanael@jada.org': 462, 'Nicklaus@talon.io': 463, 'Jerald@laura.io': 464,
         'Jamey_Dare@johnny.org': 465, 'Brant@yasmin.co.uk': 466, 'Adrianna_Howell@molly.io': 467,
         'Amiya.Morar@emma.tv': 468, 'Destany@bailey.info': 469, 'Katarina.Wolff@joel.io': 470, 'Pearline@veda.ca': 471,
         'Belle.Braun@otis.name': 472, 'Eliane@libby.net': 473, 'Trey.Harber@christop.biz': 474,
         'Kailyn@ivory.info': 475, 'Amely.Kunde@rodrigo.co.uk': 476, 'Thaddeus.Halvorson@ruthe.ca': 477,
         'Hannah@emma.ca': 478, 'Maryam.Mann@thelma.info': 479, 'Michel@keira.us': 480, 'Domenick@russell.ca': 481,
         'Chanelle@samson.me': 482, 'Hermann.Kunde@rosina.us': 483, 'Olen@bryce.net': 484,
         'Lorenza.Carter@consuelo.ca': 485, 'Lamont@georgiana.biz': 486, 'Colin_Gutkowski@muriel.net': 487,
         'Albert@johnny.biz': 488, 'Hilma.Kutch@ottilie.info': 489, 'Donnie@alfreda.biz': 490,
         'Maxwell@adeline.me': 491, 'Amina@emmet.org': 492, 'Gilda@jacques.org': 493, 'Kadin@walter.io': 494,
         'Alice_Considine@daren.com': 495, 'Zola@lizzie.com': 496, 'Dolly@mandy.co.uk': 497, 'Davion@eldora.net': 498,
         'Wilburn_Labadie@araceli.name': 499, 'Emma@joanny.ca': 500}


# # The below logic has been used to fetching all user emails from the given data
#
# import requests
#
# # Fetch posts data
# posts_response = requests.get('https://jsonplaceholder.typicode.com/posts')
# posts_data = posts_response.json()
#
# # Initialize a set to store unique email IDs
# users = {}
#
# user_id = 0
# # Iterate through each post
# for post in posts_data:
#     # Fetch comments data for the post
#     comments_response = requests.get(f'https://jsonplaceholder.typicode.com/comments?postId={post["id"]}')
#     comments_data = comments_response.json()
#
#     # Iterate through each comment
#     for comment in comments_data:
#         user_id += 1
#         # Add the email ID to the set
#         if comment["email"] not in users:
#             users[comment['email']] = user_id
#
# # Convert the set to a list
# # users = list(unique_emails)
# print(users)
